language: php

php:
    - 5.4

before_script:
    - pecl install imagick
    - "mkdir -p ~/.composer"
    - cp .travis.composer.config.json ~/.composer/config.json
    - composer install --dev

script: php ./bin/atoum -ncc