parameters:
    database_driver:    pdo_sqlite
    # database_host:      127.0.0.1
    # database_port:      ~
    # database_name:      symfony
    # database_user:      root
    # database_password:  ~
    database_path:      %kernel.root_dir%/data/musql.sqlite

    mailer_transport:   smtp
    mailer_host:        127.0.0.1
    mailer_user:        ~
    mailer_password:    ~

    locale:             en
    secret:             bohpekaim2ahyi1aecam1Siecaish8Uin3oom4oochahgahvie7oweoshain1eec

    muse.cache.root_path:       %kernel.root_dir%/../data/cache
    muse.gallery.root_path:     %kernel.root_dir%/../data/gallery
    muse.default.item_per_page: 50
    muse.default.thumb.width:   150
    muse.default.thumb.height:  150