<?php

namespace Mattlab\MuseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProtectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtectionRepository extends EntityRepository
{
}
