Home:
    path:   /
    defaults:
        _controller:    Muse\Controller\Album::displayAction
        albumPath:      ''
        page:           1
        nbPerPage:      50



AlbumDisplay:
    path:   /album/{page}-{nbPerPage}/{albumPath}
    defaults:
        _controller:    Muse\Controller\Album::displayAction
        page:           1
        nbPerPage:      50
    requirements:
        albumPath:      .*
        page:           "[0-9]+"
        nbPerPage:      "[0-9]+"

AlbumProtect:
    path:       /album/protect/{albumPath}
    methods:    GET
    defaults:
        _controller:    Muse\Controller\Album::protectAction
    requirements:
        albumPath:      .*

AlbumCrypt:
    path:       /album/crypt/{albumPath}
    methods:    POST
    defaults:
        _controller:    Muse\Controller\Album::cryptAction
    requirements:
        albumPath:      .*

AlbumUnprotect:
    path:       /album/unprotect/{albumPath}
    methods:    GET
    defaults:
        _controller:    Muse\Controller\Album::unprotectAction
    requirements:
        albumPath:      .*

AlbumDecrypt:
    path:       /album/decrypt/{albumPath}
    methods:    POST
    defaults:
        _controller:    Muse\Controller\Album::decryptAction
    requirements:
        albumPath:      .*



PhotoThumb:
    path:   /photo/{width}x{height}/{photo}
    defaults:
        _controller:    Muse\Controller\Photo::thumbAction
    requirements:
        photo:          .*
        width:          "[0-9]+"
        height:         "[0-9]+"

PhotoDisplay:
    path:   /photo/{photo}
    defaults:
        _controller:    Muse\Controller\Photo::displayAction
    requirements:
        photo:          .*



UserSignIn:
    path:       /signin
    methods:    GET
    defaults:
        _controller:    Muse\Controller\User::signInAction

UserLogin:
    path:       /login
    methods:    POST
    defaults:
        _controller:    Muse\Controller\User::loginAction
    requirements:
        login:          .*
        password:       .*

UserSignOut:
    path:       /signout
    methods:    GET
    defaults:
        _controller:    Muse\Controller\User::signOutAction